name: QuietlyApp
options:
  bundleIdPrefix: com.quietly
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  QuietlyApp:
    type: application
    platform: iOS
    sources:
      - path: QuietlyApp
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wolfgangpeters.quietlyapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: QuietlyApp/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: QuietlyApp/QuietlyApp.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
    capabilities:
      iCloud:
        enabled: true
        cloudKit: true
        containers:
          - iCloud.com.wolfgangpeters.quietlyapp
    dependencies:
      - target: ReadingWidgetExtension

  ReadingWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ReadingWidget
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wolfgangpeters.quietlyapp.ReadingWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: ReadingWidget/Info.plist
        GENERATE_INFOPLIST_FILE: false
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
